name: retinotopy
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.6
  - anaconda
  - pip
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - statsmodels
  - pandas
  - pyyaml
  - snakemake>=5.4
  - pip:
      - pybids >= 0.7.0
      - neuropythy >= 0.9.0
